language: c

before_install:
   - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
   - chmod 755 ./pkg-build.sh
   - ./pkg-build.sh bootstrap

install:
# - ./travis-tool.sh install_bioc_deps
   # Install binary pandoc from Rstudio
   - export PATH="$HOME/pandoc:$PATH"
   - mkdir $HOME/pandoc
   - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
   - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
   -d $HOME/pandoc
   - chmod +x $HOME/pandoc/pandoc
   - pandoc --version
   # Install bioc deps
   - ./pkg-build.sh install_bioc_deps

script:
# - ./travis-tool.sh run_tests
   - ./pkg-build.sh run_build
   - ./pkg-build.sh run_check
   
after_failure:
# - ./travis-tool.sh dump_logs
   - ./pkg-build.sh dump_logs

after_script:
# - ./travis-tool.sh dump_logs_by_extension "timings"
# - ./travis-tool.sh dump_sysinfo
   - ./pkg-build.sh dump_logs_by_extension "timings"
   - ./pkg-build.sh dump_sysinfo

notifications:
   email:
    on_success: change
    on_failure: change
   slack:
    secure: FIA40TI4UkOHvR19rNCfX1la5tiCmyEMjiO/sGyK0cWGt5qQxIOp+PHE3pOk9axYiVacbSCR3oAosQUsOxRew/6FyMsNR3bCPXVUzrIimABvBbjofMBDx3Z7W03O+6YahmHwDrJEWDuJ0k4457QqeqhITcFWX4twieo5fJCjedI=

env:
   global:
   - RVERSION=3.1.0
   - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
   - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
#  - R_CHECK_TIME="TRUE"
   - R_CHECK_TESTS="TRUE"
   - _R_CHECK_TIMINGS_="0"
